/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ConnectDatabase.DBConnect;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ND
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
       
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/icon/logodkhp.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jbthoat = new javax.swing.JButton();
        jbdangnhap = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 400));
        setMinimumSize(new java.awt.Dimension(324, 282));
        setResizable(false);
        setSize(new java.awt.Dimension(374, 282));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 84, 109));
        jPanel1.setLayout(null);

        jbthoat.setBackground(new java.awt.Color(0, 102, 255));
        jbthoat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbthoat.setForeground(new java.awt.Color(255, 255, 255));
        jbthoat.setText("Thoát");
        jbthoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbthoat.setPreferredSize(new java.awt.Dimension(122, 29));
        jbthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbthoatActionPerformed(evt);
            }
        });
        jPanel1.add(jbthoat);
        jbthoat.setBounds(370, 460, 130, 40);

        jbdangnhap.setBackground(new java.awt.Color(0, 102, 255));
        jbdangnhap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbdangnhap.setForeground(new java.awt.Color(255, 255, 255));
        jbdangnhap.setText("Đăng Nhập");
        jbdangnhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbdangnhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdangnhapActionPerformed(evt);
            }
        });
        jbdangnhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbdangnhapKeyReleased(evt);
            }
        });
        jPanel1.add(jbdangnhap);
        jbdangnhap.setBounds(220, 460, 130, 40);

        jPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(37, 64, 91), 3, true));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordKeyReleased(evt);
            }
        });
        jPanel1.add(jPassword);
        jPassword.setBounds(270, 380, 230, 40);

        jUsername.setToolTipText("");
        jUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(37, 64, 91), 3, true));
        jUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jUsernameKeyReleased(evt);
            }
        });
        jPanel1.add(jUsername);
        jUsername.setBounds(270, 320, 230, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/password.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 380, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 320, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\BTL JAVA\\login.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-9, -4, 760, 600);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyReleased
        if (evt.getKeyCode()==evt.VK_ENTER) {
            send();
        }
    }//GEN-LAST:event_jPasswordKeyReleased

    private void jUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jPassword.requestFocus();

        }
    }//GEN-LAST:event_jUsernameKeyReleased

    private void jbdangnhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbdangnhapKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode()==evt.VK_ENTER) {
            send();
        }
    }//GEN-LAST:event_jbdangnhapKeyReleased

    private void jbdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdangnhapActionPerformed
        send();
    }//GEN-LAST:event_jbdangnhapActionPerformed

    private void jbthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbthoatActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jbthoatActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed
/*Code Here*/
     public static String nameLogin = "";
     public static String thongBaoMatKhau = "";
    
     
    PreparedStatement ps = null;
    ResultSet rs= null;
    public void resetForm() {
        jUsername.setText("");
        jPassword.setText("");
        jUsername.requestFocus();
    }

    public void send() {
        String strnull = "";
        String user = jUsername.getText();
        String pass = jPassword.getText();
        if (user.equals(strnull) || pass.equals(strnull)) {
            JOptionPane.showMessageDialog(null, "Tài khoản và mật khẩu không được trống !");
            this.resetForm();
        } else if (DBConnect.open()) {
            try {
                boolean blean = true;
                ps = DBConnect.cnn.prepareStatement("select TenTK,MatKhau from TaiKhoan ");
                rs = ps.executeQuery();
                do  {
                    rs.next();
                    String username =""+rs.getString("TenTK");
                    String password =""+rs.getString("MatKhau");
                   
                  
                    if (user.equals(username)&&pass.equals(password)&&username.substring(0, 2).equals("Ad")) {
                        
                       nameLogin = username;
                        new MainAdmin().setVisible(true);
                        break;
          
                    }
                else   
                        if (user.equals(username)&&pass.equals(password)&&username.substring(0, 2).equals("SV")) {
                        nameLogin = username;
                        new MainSV().setVisible(true);
                        dispose();
                        break;
                        
                    }
                        if(username==null){
                  
                        JOptionPane.showMessageDialog(this, "Tên người dùng hoặc mật khẩu không hợp lệ\nXin vui lòng thử lại!", "Đăng nhập thấy bại!", JOptionPane.ERROR_MESSAGE);
                        this.resetForm();
                       

                        }
                    
                    
                   
                }while(nameLogin!=null);


            } catch (SQLException ex) {
                //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Tên người dùng hoặc mật khẩu không hợp lệ\nXin vui lòng thử lại!", "Đăng nhập thấy bại!", JOptionPane.ERROR_MESSAGE);
                resetForm();
            }
        }

    }
  

                                     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new Login().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername;
    private javax.swing.JButton jbdangnhap;
    private javax.swing.JButton jbthoat;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

    
}
