/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;





import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.DateFormat;
import java.util.Calendar;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
public class MainAdmin extends javax.swing.JFrame {

    public static String nameLogin;
    public static Date today = new Date();
    public static Locale local = new Locale("vi", "VI");
    public static DateFormat d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
    public static String date = d.format(today);
    

    /**
     * Creates new form Main
     */
    public MainAdmin() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icon/logodkhp.png")).getImage());
        setUser();
        Timer dongho = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Calendar lich = Calendar.getInstance();
                int gio = lich.get(Calendar.HOUR);
                int phut = lich.get(Calendar.MINUTE);
                int giay = lich.get(Calendar.SECOND);
                jtfCurrent.setText(" " + gio + " : " + phut + " : " + giay);
            }
        });
        dongho.start();
    }

    private void setUser() {
        nameLogin = Login.nameLogin;
        jlbUser.setText(nameLogin);
        thongBaoMatKhau.setText(Login.thongBaoMatKhau);
        jlbToday.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbUser = new javax.swing.JLabel();
        jlbToday = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfCurrent = new javax.swing.JTextField();
        thongBaoMatKhau = new javax.swing.JLabel();
        jtpContent = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmHeThong = new javax.swing.JMenu();
        jmidoimatkhau = new javax.swing.JMenuItem();
        jmiLogOff = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmQuanLyKhoa = new javax.swing.JMenuItem();
        jmQuanLyChuyenNganh = new javax.swing.JMenuItem();
        jmQuanLyLop = new javax.swing.JMenuItem();
        jmTacVu = new javax.swing.JMenu();
        jmiNhapSV = new javax.swing.JMenuItem();
        jmiNhapGV = new javax.swing.JMenuItem();
        jmQuanLyHocPhan = new javax.swing.JMenuItem();
        jmQuaLyLopHocPhan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHẦN MỀM  ĐĂNG KÝ HỌC PHẦN-TRƯỜNG ĐẠI HỌC CÔNG NGHIỆP HÀ NỘI");
        setMinimumSize(new java.awt.Dimension(1106, 700));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("ID :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Ngày :");

        jlbUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbUser.setForeground(new java.awt.Color(255, 255, 255));

        jlbToday.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbToday.setForeground(new java.awt.Color(255, 255, 255));
        jlbToday.setText("Hour");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Giờ :");

        jtfCurrent.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jtfCurrent.setEnabled(false);
        jtfCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCurrentActionPerformed(evt);
            }
        });

        thongBaoMatKhau.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        thongBaoMatKhau.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)
                .addComponent(thongBaoMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbToday, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbToday)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(thongBaoMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jtpContent.setFocusCycleRoot(true);
        jtpContent.setFocusTraversalPolicyProvider(true);
        jtpContent.setFocusable(false);
        jtpContent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtpContent.setMinimumSize(new java.awt.Dimension(1106, 638));
        jtpContent.setPreferredSize(new java.awt.Dimension(1106, 638));
        jtpContent.setVerifyInputWhenFocusTarget(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);
        jtpContent.addTab("Trang Chủ", jPanel6);

        jMenuBar2.setBackground(new java.awt.Color(69, 82, 90));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar2.setToolTipText("");
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jmHeThong.setBackground(new java.awt.Color(94, 172, 175));
        jmHeThong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 82, 90)));
        jmHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/taikhoan.png"))); // NOI18N
        jmHeThong.setText("Tài Khoản");
        jmHeThong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmHeThong.setPreferredSize(new java.awt.Dimension(145, 32));

        jmidoimatkhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmidoimatkhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmidoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doimatkhau.png"))); // NOI18N
        jmidoimatkhau.setText("Đổi Mật Khẩu");
        jmidoimatkhau.setPreferredSize(new java.awt.Dimension(213, 30));
        jmidoimatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmidoimatkhauMouseClicked(evt);
            }
        });
        jmidoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmidoimatkhauActionPerformed(evt);
            }
        });
        jmHeThong.add(jmidoimatkhau);

        jmiLogOff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmiLogOff.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmiLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangxuat.png"))); // NOI18N
        jmiLogOff.setText("Đăng Xuất");
        jmiLogOff.setPreferredSize(new java.awt.Dimension(213, 30));
        jmiLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOffActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiLogOff);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmiExit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thoat.png"))); // NOI18N
        jmiExit.setText("Thoát");
        jmiExit.setPreferredSize(new java.awt.Dimension(213, 30));
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiExit);

        jMenuBar2.add(jmHeThong);

        jMenu1.setBorder(null);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/quanlycoban.png"))); // NOI18N
        jMenu1.setText("Quản Lý Cơ Bản");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(190, 32));

        jmQuanLyKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jmQuanLyKhoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmQuanLyKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        jmQuanLyKhoa.setText("Quản Lý Khoa");
        jmQuanLyKhoa.setPreferredSize(new java.awt.Dimension(213, 30));
        jmQuanLyKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyKhoaActionPerformed(evt);
            }
        });
        jMenu1.add(jmQuanLyKhoa);

        jmQuanLyChuyenNganh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmQuanLyChuyenNganh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmQuanLyChuyenNganh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        jmQuanLyChuyenNganh.setText("Quản Lý Chuyên Ngành");
        jmQuanLyChuyenNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyChuyenNganhActionPerformed(evt);
            }
        });
        jMenu1.add(jmQuanLyChuyenNganh);

        jmQuanLyLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jmQuanLyLop.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmQuanLyLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        jmQuanLyLop.setText("Quản Lý Lớp");
        jmQuanLyLop.setPreferredSize(new java.awt.Dimension(213, 30));
        jmQuanLyLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyLopActionPerformed(evt);
            }
        });
        jMenu1.add(jmQuanLyLop);

        jMenuBar2.add(jMenu1);

        jmTacVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/quanlydaotao .png"))); // NOI18N
        jmTacVu.setText("Quản Lý Đào Tạo");
        jmTacVu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmTacVu.setPreferredSize(new java.awt.Dimension(190, 32));

        jmiNhapSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapSV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmiNhapSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmiNhapSV.setText("Quản Lý Sinh Viên");
        jmiNhapSV.setPreferredSize(new java.awt.Dimension(213, 30));
        jmiNhapSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiNhapSVMouseClicked(evt);
            }
        });
        jmiNhapSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapSVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapSV);

        jmiNhapGV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapGV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmiNhapGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmiNhapGV.setText("Quản Lý Giáo Viên");
        jmiNhapGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapGVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapGV);

        jmQuanLyHocPhan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jmQuanLyHocPhan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmQuanLyHocPhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmQuanLyHocPhan.setText("Quản Lý Học Phần");
        jmQuanLyHocPhan.setPreferredSize(new java.awt.Dimension(213, 30));
        jmQuanLyHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyHocPhanActionPerformed(evt);
            }
        });
        jmTacVu.add(jmQuanLyHocPhan);

        jmQuaLyLopHocPhan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jmQuaLyLopHocPhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmQuaLyLopHocPhan.setText("Quản Lý Lớp Học Phần");
        jmQuaLyLopHocPhan.setPreferredSize(new java.awt.Dimension(213, 30));
        jmQuaLyLopHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuaLyLopHocPhanActionPerformed(evt);
            }
        });
        jmTacVu.add(jmQuaLyLopHocPhan);

        jMenuBar2.add(jmTacVu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jtpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtpContent.getAccessibleContext().setAccessibleName("Trang Chủ");

        setSize(new java.awt.Dimension(1605, 936));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiNhapSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapSVActionPerformed
                // TODO add your handling code here:
        QuanLySinhVien sinhVien = new QuanLySinhVien();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Sinh Viên", sinhVien);
        //jPanel6.add("SV", sinhVien);
       // sinhVien.setVisible(true);
       // sinhVien.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        sinhVien.LamMoi();



    }//GEN-LAST:event_jmiNhapSVActionPerformed

    private void jmQuanLyKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyKhoaActionPerformed
        
        try{
            QuanLyKhoa khoa = new QuanLyKhoa();
            jtpContent.removeAll();
            jtpContent.add("Quản Lý Khoa",khoa);
//            khoa.setVisible(true);
//            khoa.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
            khoa.LamMoi();
        }catch(IllegalArgumentException e){
        
        }
       
    }//GEN-LAST:event_jmQuanLyKhoaActionPerformed

    private void jmiNhapGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapGVActionPerformed
        QuanLyGiangVien giangVien = new QuanLyGiangVien();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Giảng Viên",giangVien);
//        giangVien.setVisible(true);
//        giangVien.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        giangVien.LamMoi();

    }//GEN-LAST:event_jmiNhapGVActionPerformed

    private void jmQuanLyChuyenNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyChuyenNganhActionPerformed

        try{
        QuanLyChuyenNganh chuyennganh = new QuanLyChuyenNganh();
        jtpContent.removeAll();
       // chuyennganh.setVisible(true);
       jtpContent.add("Quản Lý Chuyên Ngành", chuyennganh);
       //chuyennganh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        chuyennganh.LamMoi();
        }catch(IllegalArgumentException e){
        
        }
    }//GEN-LAST:event_jmQuanLyChuyenNganhActionPerformed

    private void jmiLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOffActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jmiLogOffActionPerformed

    private void jmidoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmidoimatkhauActionPerformed
        jtpContent.removeAll();
        DoiMatKhau ld=new DoiMatKhau();
        ld.show();
        ld.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
    }//GEN-LAST:event_jmidoimatkhauActionPerformed

    private void jtfCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCurrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCurrentActionPerformed

    private void jmQuanLyLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyLopActionPerformed
        try{
        QuanLyLopHoc lophoc = new QuanLyLopHoc();
        jtpContent.removeAll();
        //lophoc.setVisible(true);
        jtpContent.add("Quản Lý Lớp Học", lophoc);
        //lophoc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        lophoc.LamMoi();
        }catch(IllegalArgumentException e){
        
        }
    }//GEN-LAST:event_jmQuanLyLopActionPerformed

    private void jmQuanLyHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyHocPhanActionPerformed
        try{      
        QuanLyHocPhan hocphan =new QuanLyHocPhan();      
       jtpContent.removeAll();
       jtpContent.add("Quản Lý Học Phần",hocphan);
      // hocphan.setVisible(true);
      // hocphan.show();
      // hocphan.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
       hocphan.LamMoi();
       }catch(IllegalArgumentException e){
        
        }

    }//GEN-LAST:event_jmQuanLyHocPhanActionPerformed

    private void jmQuaLyLopHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuaLyLopHocPhanActionPerformed
       QuanLyLopHocPhan lophocphan =new QuanLyLopHocPhan();
       jtpContent.removeAll();
       jtpContent.add("Quản Lý Lớp Học Phần",lophocphan);
       //lophocphan.setVisible(true);
       lophocphan.LamMoi();

    }//GEN-LAST:event_jmQuaLyLopHocPhanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void jmiNhapSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiNhapSVMouseClicked
        // TODO add your handling code here:
       // jmiNhapSVActionPerformed(evt);
    }//GEN-LAST:event_jmiNhapSVMouseClicked

    private void jmidoimatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmidoimatkhauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmidoimatkhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jlbToday;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JMenu jmHeThong;
    private javax.swing.JMenuItem jmQuaLyLopHocPhan;
    private javax.swing.JMenuItem jmQuanLyChuyenNganh;
    private javax.swing.JMenuItem jmQuanLyHocPhan;
    private javax.swing.JMenuItem jmQuanLyKhoa;
    private javax.swing.JMenuItem jmQuanLyLop;
    private javax.swing.JMenu jmTacVu;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogOff;
    private javax.swing.JMenuItem jmiNhapGV;
    private javax.swing.JMenuItem jmiNhapSV;
    private javax.swing.JMenuItem jmidoimatkhau;
    private javax.swing.JTextField jtfCurrent;
    private javax.swing.JTabbedPane jtpContent;
    private javax.swing.JLabel thongBaoMatKhau;
    // End of variables declaration//GEN-END:variables

    
}
