/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CustomTable.CustomTableSinhVien;
import DAO.ILopHocDAO;
import DAO.ISinhVienDAO;
import DAO.LopHocDAO;
import DAO.SinhVienDAO;
import Entity.LopHoc;
import Entity.SinhVien;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class QuanLySinhVien extends javax.swing.JPanel {

    /**
     * Creates new form QuanLySinhVien
     */
     private String masv, tensv, malop, hedt, ngaysinh, gioitinh, diachi;
    int selectedRow=-1;
    ArrayList<SinhVien> li=new ArrayList<>();
    public QuanLySinhVien() {
        initComponents();
         //setLocationRelativeTo(null);
          LoadData();
    }
    public void LoadTable(){
        jTableSinhVien.setModel(new CustomTableSinhVien(li));
    }
    private void LoadData() {
        try {
            ISinhVienDAO sinhVienDAO = (ISinhVienDAO) Class.forName("DAO.SinhVienDAO").newInstance();
            li = new SinhVienDAO().getAll();
            LoadTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(GUI.QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(GUI.QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void LamMoi(){
        txtMaSV.setText("");
        txtTenSV.setText("");
        jComboBoxMaLop.setSelectedItem("CNTT1");
        jComboBoxHDT.setSelectedItem("Đại học");
        txtNgaySinh.setText("");
        buttonGroup1.clearSelection();
        txtDiaChi.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        Them = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        LamMoi = new javax.swing.JButton();
        HienThiLai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSinhVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtTenSV = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jComboBoxMaLop = new javax.swing.JComboBox<>();
        jComboBoxHDT = new javax.swing.JComboBox<>();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Them.setBackground(new java.awt.Color(0, 153, 255));
        Them.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Them.setText("Thêm");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Sua.setBackground(new java.awt.Color(0, 153, 255));
        Sua.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Sua.setText("Sửa");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        Xoa.setBackground(new java.awt.Color(0, 153, 255));
        Xoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        LamMoi.setBackground(new java.awt.Color(0, 153, 255));
        LamMoi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LamMoi.setText("Làm mới");
        LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiActionPerformed(evt);
            }
        });

        HienThiLai.setBackground(new java.awt.Color(0, 153, 255));
        HienThiLai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        HienThiLai.setText("Hiển thị danh sách");
        HienThiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HienThiLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HienThiLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sua)
                .addGap(18, 18, 18)
                .addComponent(Xoa)
                .addGap(18, 18, 18)
                .addComponent(LamMoi)
                .addGap(18, 18, 18)
                .addComponent(HienThiLai)
                .addContainerGap())
        );

        jLabel3.setText("(Tìm kiếm sinh viên theo mã lớp)");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        btnTim.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTim.setText("Tìm kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jTableSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSinhVien);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Mã sinh viên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Tên sinh viên:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Mã lớp:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Hệ đào tạo:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Địa chỉ:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Ngày sinh:");

        jComboBoxMaLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT001", "CNTT002", "CNTT003", "KHMT001", "KHMT002", "HTTT001", "HHTT002", "DULICH001", "DULICH002", "QTKD001", "QTKD002" }));

        jComboBoxHDT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đại học", "Cao đẳng" }));

        buttonGroup1.add(radNam);
        radNam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        radNam.setText("Nam");

        buttonGroup1.add(radNu);
        radNu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        radNu.setText("Nữ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Giới tính:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(77, 77, 77))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxMaLop, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxHDT, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(radNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(radNu))
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radNam)
                            .addComponent(radNu)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxHDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTim)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
         // TODO add your handling code here:
        try{
            if(radNam.isSelected()||radNu.isSelected()){
            if(txtMaSV.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Mã sinh viên không được để trống"); 
            }
            else if(txtTenSV.getText().equals("")||txtNgaySinh.getText().equals("")||txtDiaChi.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Điền đầy đủ thông tin của sinh viên trước khi thêm");
            }
            else{
                masv=txtMaSV.getText();
                tensv=txtTenSV.getText();
                malop=jComboBoxMaLop.getSelectedItem()+"";
                hedt=jComboBoxHDT.getSelectedItem()+"";
                ngaysinh=txtNgaySinh.getText();
                if(radNam.isSelected())
                    gioitinh="Nam";
                if(radNu.isSelected())
                    gioitinh="Nữ";
                diachi=txtDiaChi.getText();
                SinhVien check=new SinhVien(masv);
                if(li.contains(check)){
                        JOptionPane.showMessageDialog(null, "Mã sinh viên bị trùng, không thể thêm sinh viên này vào danh sách sinh viên");
                    }
                    else{
                        SinhVien sv=new SinhVien(masv,tensv,malop,hedt,ngaysinh,gioitinh,diachi);
                        SinhVien add=new SinhVienDAO().addNew(sv);
                        JOptionPane.showMessageDialog(null, "Thêm sinh viên thành công"); 
                        LoadData();
                    }
                LamMoi();
                }
            }
            else
                 JOptionPane.showMessageDialog(null, "Giới tính không được để trống"); 
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Điền đầy đủ thông tin của sinh viên trước khi thêm");
        }
    }//GEN-LAST:event_ThemActionPerformed

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        // TODO add your handling code here:
         try{
            if(radNam.isSelected()||radNu.isSelected()){
            if(txtMaSV.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Mã sinh viên không được để trống"); 
            }
            else if(txtTenSV.getText().equals("")||txtNgaySinh.getText().equals("")||txtDiaChi.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Điền đầy đủ thông tin của sinh viên trước khi sửa");
            }
            else{
                String ma=txtMaSV.getText();
                selectedRow=jTableSinhVien.getSelectedRow();
                masv=txtMaSV.getText();
                tensv=txtTenSV.getText();
                malop=jComboBoxMaLop.getSelectedItem()+"";
                hedt=jComboBoxHDT.getSelectedItem()+"";
                ngaysinh=txtNgaySinh.getText();
                if(radNam.isSelected())
                    gioitinh="Nam";
                if(radNu.isSelected())
                    gioitinh="Nữ";
                diachi=txtDiaChi.getText();
                SinhVien svm=new SinhVien(masv,tensv,malop,hedt,ngaysinh,gioitinh,diachi);
                SinhVien sv=new SinhVien(ma);
                    if(li.contains(sv)){
                        li.set(li.indexOf(sv), svm);
                        SinhVien update=new SinhVienDAO().updateByMaSV(svm);
                        JOptionPane.showMessageDialog(null, "Sửa thông tin sinh viên thành công"); 
                    }
                    else
                        JOptionPane.showMessageDialog(null,"Không cập nhật được thông tin cho sinh viên có mã "+ma);
                LamMoi();
                LoadTable();
            }   
            }
             else
                 JOptionPane.showMessageDialog(null, "Giới tính không được để trống"); 
             }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Điền đầy đủ thông tin của sinh viên trước khi sửa");
        }
    }//GEN-LAST:event_SuaActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
       if(jTableSinhVien.getRowCount()==0){
             JOptionPane.showMessageDialog(null, "Danh sách rỗng");
        }
        else{
            String ma=txtMaSV.getText();
            SinhVien sv=new SinhVien(ma);
            if(li.contains(sv)){
                int chose=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa sinh viên này?","Thông báo",
                        JOptionPane.YES_NO_OPTION);
                if(chose==JOptionPane.YES_OPTION){
                    li.remove(li.indexOf(sv));
                    try {
                        new SinhVienDAO().deleteMaSV(ma);
                        new SinhVienDAO().deleteUserSV(ma);
                        JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                    } catch (SQLException ex) {
                        Logger.getLogger(GUI.QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(GUI.QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    LoadTable();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Sinh viên có mã "+ma+" không có trong danh sách");
            }
        }
       LamMoi();
    }//GEN-LAST:event_XoaActionPerformed

    private void LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiActionPerformed
        // TODO add your handling code here:
        LamMoi();
    }//GEN-LAST:event_LamMoiActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String malopTim=txtTim.getText();
        ArrayList<SinhVien> list=new ArrayList<>();
        for(SinhVien sv:li){
            if(sv.getMaLop().equals(malopTim))
                list.add(sv);
        }
        li.clear();
        li.addAll(list);
        jTableSinhVien.setModel(new CustomTableSinhVien(li));
    }//GEN-LAST:event_btnTimActionPerformed

    private void jTableSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSinhVienMouseClicked
        // TODO add your handling code here:
        selectedRow=jTableSinhVien.getSelectedRow();
        SinhVien sv=li.get(selectedRow);
        txtMaSV.setText(sv.getMaSinhVien()+"");
        txtTenSV.setText(sv.getTenSinhVien()+"");
        jComboBoxMaLop.setSelectedItem(sv.getMaLop()+"");
        jComboBoxHDT.setSelectedItem(sv.getHeDT()+"");
        txtNgaySinh.setText(sv.getNgaySinh()+"");
        if(sv.getGioitinh().equals("Nam"))
        {
            radNam.setSelected(true);
            radNu.setSelected(false);
        }
        if(sv.getGioitinh().equals("Nữ"))
        {
            radNam.setSelected(false);
            radNu.setSelected(true);
        }
        txtDiaChi.setText(sv.getDiaChi());
        
    }//GEN-LAST:event_jTableSinhVienMouseClicked

    private void HienThiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HienThiLaiActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_HienThiLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HienThiLai;
    private javax.swing.JButton LamMoi;
    private javax.swing.JButton Sua;
    private javax.swing.JButton Them;
    private javax.swing.JButton Xoa;
    private javax.swing.JButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxHDT;
    private javax.swing.JComboBox<String> jComboBoxMaLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSinhVien;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenSV;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
