/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CustomTable.CustomTableLopHocPhan;
import DAO.HocPhanDAO;
import DAO.IHocPhanDAO;
import DAO.ILopHocPhanDAO;
import DAO.LopHocPhanDAO;
import Entity.HocPhan;
import Entity.LopHocPhan;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class QuanLyLopHocPhan extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyLopHocPhan
     */
    private String malophp,mahp,magv,tiethoc,thu,ngaybd,diadiem;
    int selectedRow=-1;
    ArrayList<LopHocPhan> li=new ArrayList<>();
    ArrayList<HocPhan> listhocphan= new ArrayList<>();
    public QuanLyLopHocPhan() {
        initComponents();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void LoadTable(){
        jTableLHP.setModel(new CustomTableLopHocPhan(li));
    }
    public void LoadData(){
        try{
            IHocPhanDAO hocPhanDAO = (IHocPhanDAO) Class.forName("DAO.HocPhanDAO").newInstance();
            listhocphan = new HocPhanDAO().getAll();//Lấy dữ liệu từ bảng HocPhan trong CSDL
            ILopHocPhanDAO lopHocPhanDAO = (ILopHocPhanDAO) Class.forName("DAO.LopHocPhanDAO").newInstance();
            li = new LopHocPhanDAO().getAll();//Lấy dữ liệu từ bảng LopHocPhan trong CSDL
            LoadTable();
        } catch (InstantiationException ex) {
            Logger.getLogger(QuanLyLopHocPhan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(QuanLyLopHocPhan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyLopHocPhan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void FindDataByMa(){
        try{
            String tim=txtTim.getText();
            ILopHocPhanDAO lopHocPhanDAO = (ILopHocPhanDAO) Class.forName("DAO.LopHocPhanDAO").newInstance();
            li = new LopHocPhanDAO().findByMaHP(tim);
            LoadTable();
        } catch (InstantiationException ex) {
            Logger.getLogger(QuanLyLopHocPhan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(QuanLyLopHocPhan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyLopHocPhan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void LamMoi(){
        txtMaLHP.setText("");
        txtMaHP.setText("");
        txtMaGV.setText("");
        txtTietHoc.setText("");
        jComboBoxThu.setSelectedItem("Thứ 2");
        txtNgayBD.setText("");
        txtDiaDiem.setText("");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLHP = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaLHP = new javax.swing.JTextField();
        txtNgayBD = new javax.swing.JTextField();
        txtMaHP = new javax.swing.JTextField();
        txtMaGV = new javax.swing.JTextField();
        txtTietHoc = new javax.swing.JTextField();
        txtDiaDiem = new javax.swing.JTextField();
        jComboBoxThu = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        Them = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        Lammoi = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        HienThiLai = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtTim = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTableLHP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLHP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLHPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLHP);

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ DANH SÁCH LỚP HỌC PHẦN");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Mã lớp học phần:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Mã học phần:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Tiết học:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Mã giảng viên:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Địa điểm:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Ngày bắt đầu:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Thứ học:");

        jComboBoxThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7", "Chủ Nhật" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTietHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHP, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxThu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(txtMaLHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(txtMaHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTietHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Them.setBackground(new java.awt.Color(0, 153, 255));
        Them.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Them.setText("Thêm");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Sua.setBackground(new java.awt.Color(0, 153, 255));
        Sua.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Sua.setText("Sửa");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        Lammoi.setBackground(new java.awt.Color(0, 153, 255));
        Lammoi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Lammoi.setText("Làm Mới");
        Lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LammoiActionPerformed(evt);
            }
        });

        Xoa.setBackground(new java.awt.Color(0, 153, 255));
        Xoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        HienThiLai.setBackground(new java.awt.Color(0, 153, 255));
        HienThiLai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        HienThiLai.setText("Hiển Thị Danh Sách");
        HienThiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HienThiLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HienThiLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Them)
                .addGap(18, 18, 18)
                .addComponent(Sua)
                .addGap(18, 18, 18)
                .addComponent(Xoa)
                .addGap(18, 18, 18)
                .addComponent(Lammoi)
                .addGap(21, 21, 21)
                .addComponent(HienThiLai)
                .addContainerGap())
        );

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Tìm kiếm lớp học phần theo mã học phần");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        FindDataByMa();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jTableLHPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLHPMouseClicked
        // TODO add your handling code here:
        selectedRow=jTableLHP.getSelectedRow();
        LopHocPhan lhp=li.get(selectedRow);
        txtMaLHP.setText(lhp.getMaLHP()+"");
        txtMaHP.setText(lhp.getMaHP()+"");
        txtMaGV.setText(lhp.getMaGV()+"");
        txtTietHoc.setText(lhp.getTietHoc()+"");
        jComboBoxThu.setSelectedItem(lhp.getThu()+"");
        txtNgayBD.setText(lhp.getNgayBatDau()+"");
        txtDiaDiem.setText(lhp.getDiaDiem()+"");
    }//GEN-LAST:event_jTableLHPMouseClicked

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaLHP.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Mã lớp học phần không được để trống");
            }
            else if(txtMaHP.getText().equals("")||txtMaGV.getText().equals("")||txtTietHoc.getText().equals("")
                ||txtNgayBD.getText().equals("")||txtDiaDiem.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Điền đầy đủ thông tin của sinh viên trước khi thêm");
            }
            else{
                malophp=txtMaLHP.getText();
                mahp=txtMaHP.getText();
                magv=txtMaGV.getText();
                tiethoc=txtTietHoc.getText();
                thu=(String) jComboBoxThu.getSelectedItem();
                ngaybd=txtNgayBD.getText();
                diadiem=txtDiaDiem.getText();
                LopHocPhan check=new LopHocPhan(malophp);
                if(li.contains(check)){
                    JOptionPane.showMessageDialog(null, "Mã lớp học phần bị trùng,không thể thêm lớp học phần này ");
                }
                else{
                    LopHocPhan lhp=new LopHocPhan(malophp,mahp,magv,tiethoc,thu,ngaybd,diadiem);
                    LopHocPhan add=new LopHocPhanDAO().addNew(lhp);
                    LoadData();
                    JOptionPane.showMessageDialog(null, "Thêm thành công ");
                }
                LamMoi();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Điền đầy đủ thông tin của sinh viên trước khi thêm");
        }
    }//GEN-LAST:event_ThemActionPerformed

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        // TODO add your handling code here:
         try{
            if(txtMaLHP.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Mã lớp học phần không được để trống");
            }
            else if(txtMaHP.getText().equals("")||txtMaGV.getText().equals("")||txtTietHoc.getText().equals("")
                ||txtNgayBD.getText().equals("")||txtDiaDiem.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Điền đầy đủ thông tin của sinh viên trước khi sửa");
            }
            else{
                String ma=txtMaLHP.getText();
                selectedRow=jTableLHP.getSelectedRow();
                malophp=txtMaLHP.getText();
                mahp=txtMaHP.getText();
                magv=txtMaGV.getText();
                tiethoc=txtTietHoc.getText();
                thu=(String) jComboBoxThu.getSelectedItem();
                ngaybd=txtNgayBD.getText();
                diadiem=txtDiaDiem.getText();
                LopHocPhan lhpm=new LopHocPhan(malophp,mahp,magv,tiethoc,thu,ngaybd,diadiem);
                    LopHocPhan lhp=new LopHocPhan(ma);

                    if(li.contains(lhp)){
                        li.set(li.indexOf(lhp), lhpm);
                        LopHocPhan update=new LopHocPhanDAO().updateByMa(lhpm);
                        LoadData();
                         JOptionPane.showMessageDialog(null, "Sửa thành công ");
                    }
                    else
                         JOptionPane.showMessageDialog(null,"Không cập nhật được thông tin cho lớp học phần có mã "+ma);
                   LamMoi();
           
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Điền đầy đủ thông tin của sinh viên trước khi sửa");
        }
      
    }//GEN-LAST:event_SuaActionPerformed

    private void LammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LammoiActionPerformed
        // TODO add your handling code here:
        LamMoi();
    }//GEN-LAST:event_LammoiActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
        if(jTableLHP.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Danh sách rỗng");
        }
        else{
            String ma=txtMaLHP.getText();
            LopHocPhan lhp=new LopHocPhan(ma);
            if(li.contains(lhp)){
                int chose=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa lớp học phần này?","Thông báo",
                    JOptionPane.YES_NO_OPTION);
                if(chose==JOptionPane.YES_OPTION){
                    li.remove(li.indexOf(lhp));
                    LoadTable();
                    try {
                        new LopHocPhanDAO().deleteLopHocPhan(ma);
                        JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Dữ liệu không thể xóa , sinh viên trong lớp học phần này đã có điểm!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Dữ liệu không thể xóa, sinh viên trong lớp học phần này đã có điểm!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Lớp học phần có mã "+ma+" không có trong danh sách");
            }
        }
    }//GEN-LAST:event_XoaActionPerformed

    private void HienThiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HienThiLaiActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_HienThiLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HienThiLai;
    private javax.swing.JButton Lammoi;
    private javax.swing.JButton Sua;
    private javax.swing.JButton Them;
    private javax.swing.JButton Xoa;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> jComboBoxThu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLHP;
    private javax.swing.JTextField txtDiaDiem;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtMaHP;
    private javax.swing.JTextField txtMaLHP;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtTietHoc;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
